name: Lint GitHub Actions

on:
  workflow_call:
    inputs:
      advanced-security:
        description: Upload zizmor findings to GitHub Code Scanning
        type: boolean
        default: false

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ACTIONLINT_VERSION: 1.7.12
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download actionlint
        run: |
          ARCHIVE="actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          curl --proto '=https' --tlsv1.2 --fail --location --remote-name \
            "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/${ARCHIVE}"
          curl --proto '=https' --tlsv1.2 --fail --location --remote-name \
            "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_checksums.txt"
          grep " ${ARCHIVE}$" "actionlint_${ACTIONLINT_VERSION}_checksums.txt" | sha256sum --check
          tar --extract --gzip --file "$ARCHIVE" actionlint

      - name: Check workflows
        run: ./actionlint -color -ignore 'unexpected key "queue"'

  zizmor:
    if: inputs.advanced-security == false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false
          version: v1.29.0

  zizmor-code-scanning:
    if: inputs.advanced-security
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: true
          version: v1.29.0
